require("aatish.options")
require("aatish.keymaps")
require("aatish.plugins")
require("aatish.colorscheme")
require("aatish.cmp")
require("aatish.lsp")
require("aatish.luasnip")
require("aatish.telescope")
require("aatish.treesitter")
require("aatish.comment")
require("aatish.nvim-tree")
require("aatish.bufferline")
require("aatish.lualine")
require("aatish.comment")
require("aatish.autopairs")
require("aatish.null-ls")
-- require("aatish.outline")
